from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
import os
from typing import Dict, Any, List
from app.config import WORKSPACE_DIR

class PresentationTool:
    @staticmethod
    def create_presentation(
        title: str,
        subtitle: str,
        slides_content: List[Dict[str, Any]],
        output_filename: str = "Board_Presentation.pptx"
    ) -> Dict[str, Any]:
        """
        Creates a PowerPoint presentation (.pptx).
        """
        prs = Presentation()
        
        # Slide 1: Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title_box = slide.shapes.title
        subtitle_box = slide.placeholders[1]
        
        title_box.text = title
        subtitle_box.text = f"{subtitle}\nGenerated by LocalAI Sovereign Workbench"
        
        # Slide 2+: Content Slides
        bullet_layout = prs.slide_layouts[1]
        for item in slides_content:
            slide = prs.slides.add_slide(bullet_layout)
            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]
            
            title_shape.text = item.get("header", "Key Overview")
            tf = body_shape.text_frame
            
            points = item.get("points", [])
            if points:
                tf.text = points[0]
                for pt in points[1:]:
                    p = tf.add_paragraph()
                    p.text = pt
                    
        out_path = os.path.join(str(WORKSPACE_DIR), output_filename)
        prs.save(out_path)
        
        return {
            "status": "SUCCESS",
            "filename": output_filename,
            "filepath": out_path,
            "file_size_bytes": os.path.getsize(out_path)
        }
